export const DATA_GRID_VIEW_INDEX_FIELD = 'DATA_GRID_VIEW_INDEX_FIELD'
export const DATA_GRID_VIEW_CHECKBOX_FIELD = 'DATA_GRID_VIEW_CHECKBOX_FIELD'
export const DATA_GRID_VIEW_RADIO_FIELD = 'DATA_GRID_VIEW_RADIO_FIELD'
